#!/bin/bash
###############################################################################
#    Copyright (2005) Sandia Corporation.  Under the terms of Contract
#    DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
#    certain rights in this software
#
#    This file is part of Cbench.
#
#    Cbench is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    any later version.
#
#    Cbench is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Cbench; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
###############################################################################


echo -n "Today's date is: "
date +%D

# source function library
. /etc/rc.d/init.d/functions

echo 
echo -n "Checking topspin ib firmware version (v4.6.0 build 3.2.0.16):"
if [ `/usr/local/topspin/sbin/tvflash -i | grep Primary | awk '{print $4}' | cut -f1 -d','` != "v4.6.0" -a `/usr/local/topspin/sbin/tvflash -i | grep Primary | awk '{print $6}' | cut -f1 -d','` != "3.2.0.16 " ]; then
        echo_failure
else
        echo_success
fi

echo
echo -n "Checking topspin ib status:" 
if [ -d /usr/local/topspin ]; then
        /sbin/chkconfig ts_srp off
        /sbin/chkconfig ts_customize off
	if [ `/usr/local/topspin/bin/vstat | grep port_state=PORT_ACTIVE | wc -l` -ne 1 ]; then
		echo_failure
	else
		echo_success
	fi
else 
	echo_failure
fi

echo
echo -n "Checking Topspin ib driver for clean NON-LA-MPI compliance:"
if [ -f /usr/local/topspin/lib64/libvapi.so ]; then
        #if [ `strings /usr/local/topspin/lib64/libvapi.so | grep PREMAIN` = "NO_IB_PREMAIN_INIT" ]; then
	if [ `strings /usr/local/topspin/lib64/libvapi.so | grep PREMAIN | wc -l` -ne 0 ]; then
                echo_failure
        else
                echo_success
        fi
else
        echo_failure
fi
echo

