#!/bin/bash
#set -ex
###############################################################################
#    Copyright (2005) Sandia Corporation.  Under the terms of Contract
#    DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
#    certain rights in this software
#
#    This file is part of Cbench.
#
#    Cbench is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    any later version.
#
#    Cbench is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Cbench; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
###############################################################################


echo -n "Today's date is: "
date +%D

if [ -z $FIXIT123_HOME ]; then
	echo FIXIT123 environment variables not found!
	exit 1
fi

. $FIXIT123_HOME/libexec/nodechecks/os_functions
. $FIXIT123_HOME/libexec/nodechecks/dell_functions


omsa_check_bios_version A04
omsa_check_bmc_version 1.40
omsa_check_bp_version 1.00
