#!/usr/bin/perl
# vim: syntax=perl tabstop=4
###############################################################################
#    Copyright (2005) Sandia Corporation.  Under the terms of Contract
#    DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
#    certain rights in this software
#
#    This file is part of Cbench.
#
#    Cbench is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    any later version.
#
#    Cbench is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Cbench; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
###############################################################################

# Script to update the set of tests and associated utility scripts.

# install templated utility scripts

# need to know where everything cbench lives!
$BENCH_HOME = $ENV{CBENCH_SOURCE_HOME} ? $ENV{CBENCH_SOURCE_HOME} : $ENV{CBENCHOME};
die "$BENCH_HOME not defined" if !defined $BENCH_HOME;

unshift @INC, "$BENCH_HOME";
require "cbench.pl";

$bench_test = get_bench_test();
mkdir "$bench_test",0750;

foreach my $testset (@bench_tests) {
	$testset_path = "$bench_test/$testset";
	print "Updating start/gen jobs and output parser for $testset testset\n";

	# we have custom start jobs scripts to be aware of
	my $custom_script="start_jobs_jobdirs.pl";
	$custom_script = $testset . "_start_jobs.pl" if -f "$BENCH_HOME/tools/$testset" . "_start_jobs.pl";
	install_util_script("tools/$custom_script","$testset_path/$testset\_start_jobs.pl", "$testset");

	# we have some custom gen jobs to be aware of 
	$custom_script="gen_jobs_generic.pl";
	$custom_script = $testset . "_gen_jobs.pl" if -f "$BENCH_HOME/tools/$testset" . "_gen_jobs.pl";
	install_util_script("tools/$custom_script","$testset_path/$testset\_gen_jobs.pl", "$testset");

	# we have custom output parse  scripts to be aware of
	$custom_script="output_parse_generic.pl";
	$custom_script = $testset . "_output_parse.pl" if -f "$BENCH_HOME/tools/$testset" . "_output_parse.pl";
	install_util_script("tools/$custom_script","$testset_path/$testset\_output_parse.pl", "$testset");
}

