#!/bin/bash
###############################################################################
#    Copyright (2005) Sandia Corporation.  Under the terms of Contract
#    DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
#    certain rights in this software
#
#    This file is part of Cbench.
#
#    Cbench is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    any later version.
#
#    Cbench is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Cbench; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
###############################################################################

# this script installs the fixit123 svn repo into a dir

if [ $# -ne 1 ]; then
	echo "$0 DIRECTORY"
	exit 1
fi

if [ ! -d $1 ]; then
	echo "$1 is not a directory!"
	exit 1
fi

#rsync svn tree to a dir
mkdir -p $1
cd ..
rsync -a --delete --exclude .svn --exclude tools ./ $1/
chmod a+rx -R $1/bin
chmod a+rx -R $1/libexec
chmod a+rx -R $1/perllib

