#!/bin/bash

# block read testing
# give it a device and it will go after it

SLEEPDELAY=60

if [ -z "$1" ] ; then
    echo device required, maxblocks optional
    exit 1
fi
device=$1
if [ ! -z "$2" ] ; then 
    maxblocks=$2
else
    maxblocks=0
fi

size=2880
bsize=512

mount | grep "$device" >> /dev/null 2>&1
if [ $? = 0 ] ; then {
    echo cant do this on a mounted filesystem\!\!
    exit 2
} ; fi

if [ "$device" = "/dev/fd0" ] ; then
    # hack for floppy disks (no size information... grr)
    size=2880
    bsize=512
else
    scratch=`bin/print_disk_info $device`
    bsize=`echo $scratch | awk '{print $2;}'`
    size=`echo $scratch | awk '{print $1;}'`
    if [ -z "$size" -o -z "$bsize" ] ; then {
	echo Unable to configure test.  $device not present or not readable.
	exit 2
    } ; fi
fi

if [ "$size" -lt 100 ] ; then {
    echo error in size calculation... aborting
    exit 2
} ; fi

if [ "$size" -gt "$maxblocks" -a "$maxblocks" != "0" ] ; then {
    size=$maxblocks
} ; fi

if [ `basename "$0"` = "sdestructiveblocktst-info" ] ; then {
    sleep $[$RANDOM % $SLEEPDELAY]
} ; fi

echo $device $bsize $size
exit $?
