#!/bin/bash

# block rw testing in nondestructive mode
# give it a device and it will go after it


if [ -z "$3" ] ; then
    echo device bsize and size required
    exit 2
fi

bsize=$2
size=$3

./bin/flushb $1
nice -n 5 badblocks -n -b $bsize $1 $size
exit $?
