#!/bin/bash
#
###############################################################################
#    Copyright (2005) Sandia Corporation.  Under the terms of Contract
#    DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
#    certain rights in this software
#
#    This file is part of Cbench.
#
#    Cbench is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    any later version.
#
#    Cbench is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Cbench; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
###############################################################################
# vim: syntax=sh tabstop=4

# script to be executed inside the Gazebo "setUpandRun" that wraps the 
# actual running of Cbench jobs. It depends on the Gazebo test_exec config
# files being generated by the Cbench+Gazebo hook script, cbench_gazebo_submit_config.pl

#env
echo " "
echo " "
echo " "
echo "---------- Setup Cbench Environment -----------------------------------------------"
CBENCH_PPN=$PESPERNODE"ppn"
CBENCH_MATCH=$CBENCH_JOB-$CBENCH_PPN
echo "CBENCH_PPN=$CBENCH_PPN"
echo "CBENCH_MATCH=$CBENCH_MATCH"

env | egrep 'CBENCH|NPES|JOBID|GAZ'
echo " "
echo " "
echo " "

# head over to the Cbench testing tree and setup the environment for using
# that tree
cd $CBENCHTEST
. cbench-init.sh

echo "---------- Generate Cbench Job ----------------------------------------------------"
cd $CBENCH_TESTSET
./$CBENCH_TESTSET\_gen_jobs.pl --procs $NPES  --ident $CBENCH_TESTIDENT	

echo "---------- Start Cbench Job -------------------------------------------------------"
./$CBENCH_TESTSET\_start_jobs.pl --interactive --procs $NPES --match $CBENCH_MATCH --ident $CBENCH_TESTIDENT --echooutput --gazebo 2>&1 | tee $RUNHOME/temp.start
echo " "
echo " "
echo " "
echo "---------- End of Cbench Job ------------------------------------------------------"

echo " "
echo " "
echo " "
echo "---------- Parse Cbench Job Output -------------------------------------------------------"
# find the jobid identifying the cbench run
jobid=`grep "Cbench jobid:" $RUNHOME/temp.start | awk '{print $3'}`
echo "Cbench jobid was $jobid"
echo " "
echo " "
echo " "
./$CBENCH_TESTSET\_output_parse.pl --procs $NPES --ident $CBENCH_TESTIDENT --match $CBENCH_MATCH --jobid $jobid --gazebo

exit
